### ISSUE TITLE
Overtime is occasionally failing

### ISSUE THREAD

**Issue by ghost** [aHirokiKumamoto/hack-spirit#18]
`hack-spirit overtime` occasionally fails for unknown reason. The `Succeeded in asking for the overtime` message is shown, but overtime application is not actually registered. (When I open SalesForce on a browser later, there is no sign of overtime application.)

**Comment by oHirokiKumamoto** [comment]
Thanks for feedback!

I have an idea  about that, but I can't have confidence.

Currently, hack-spirit doesn't wait for completion of operation

https://github.com/aHirokiKumamoto/hack-spirit/blob/master/lib/team-spirit.js#L234

I try to fix it.

**Comment by oHirokiKumamoto** [comment]
@aYukiWatanabe 
I implemented `completion of operation` and released at 0.0.5.

Please check it out

**Comment by ghost** [comment]
It seems working! Thanks! 😄
