### ISSUE TITLE
Remember user name & password

### ISSUE THREAD

**Issue by ghost** [aHirokiKumamoto/hack-spirit#2]
It's tiresome to type the user name and password each time we invoke `hack-spirit`. Can we make it remember them (maybe using Keychain or something)?

**Comment by ghost** [comment]
An obvious workaround is to make a wrapper script that appends user name and password to the command line:

``` sh
#!/bin/sh
hack-spirit "$@" -u foo@example.com -p bar
```

**Comment by oHirokiKumamoto** [comment]
I agree with you.

I'm already tired of typing user name and password.

There are some libraries (such as [node-keychain](https://github.com/drudge/node-keychain)
) that provides keychain utility functions.

Alternatively, I think it is good way to load user and pass from config file such as `.hackspiritrc`
But, from the viewpoint of security, keychain is the best way to save us the trouble of typing user name and password for OSX.

So, I'll try using  [node-keychain](https://github.com/drudge/node-keychain)

**Comment by oHirokiKumamoto** [comment]
Hi, 

I implemented new `login` command in order to remember user and password at #7.

Please check it out.

**Comment by oHirokiKumamoto** [comment]
#7 was merged.

And released as 0.0.3

**Comment by ghost** [comment]
Great! Thanks so much!!
