### ISSUE TITLE
Non-zero exit status on failure

### ISSUE THREAD

**Issue by ghost** [aHirokiKumamoto/hack-spirit#29]
Is it possible to return a non-zero exit status when hack-spirit fails for any reasons? That would be great help when you write shell scripts.

It would also be nice for querying subcommands to indicate results via exit status. For example, `hack-spirit work_status` can return an exit status of zero when working, and a non-zero when not working.

**Comment by oHirokiKumamoto** [comment]
Thanks for your advice!

Modified by #30

For the present,  subcommand returns success ... 0, other ... 1.

If necessary, other error status need to be added.

**Comment by ghost** [comment]
Fantastic! Thank you so much!!
